php:
    - 5.6

sudo: required

before_script:
    - sudo apt-get install php-curl
    - curl -sS https://getcomposer.org/installer | php
    - sudo mv composer.phar /usr/local/bin/composer.phar
    - alias composer='/usr/local/bin/composer.phar'
    - composer install

script:
  - phpunit
